import { FINDING_CODES, type FindingCode } from "./finding-codes";
import {
  createFindingIdentity,
  type Finding,
  type FindingCategory,
  type FindingEvidence,
  type FindingLocation,
  type FindingStateImpact,
  type Repairability,
  type Severity,
} from "../models/finding";
import type { RepairKind } from "../models/repair";

export interface FindingDefinition {
  readonly severity: Severity;
  readonly category: FindingCategory;
  readonly title: string;
  readonly description: string;
  readonly stateImpact: FindingStateImpact;
  readonly repairability: Repairability | "conditional";
  readonly recommendedRepair?: RepairKind;
}

type DefinitionTuple = readonly [
  Severity,
  FindingCategory,
  FindingStateImpact,
  Repairability | "conditional",
  string,
  string,
  RepairKind?,
];

function definition([
  severity,
  category,
  stateImpact,
  repairability,
  title,
  description,
  recommendedRepair,
]: DefinitionTuple): FindingDefinition {
  return {
    severity,
    category,
    stateImpact,
    repairability,
    title,
    description,
    ...(recommendedRepair === undefined ? {} : { recommendedRepair }),
  };
}

export const FINDING_CATALOG = {
  INPUT_NOT_EPUB: definition([
    "error",
    "input",
    "unsupported",
    "none",
    "File is not an EPUB",
    "The selected basename does not use the .epub extension.",
  ]),
  INPUT_NOT_REGULAR_FILE: definition([
    "error",
    "input",
    "unsupported",
    "none",
    "Selection is not a regular file",
    "The selected item is missing or is not a regular file.",
  ]),
  INPUT_UNREADABLE: definition([
    "error",
    "input",
    "unsupported",
    "none",
    "EPUB is unreadable",
    "The selected EPUB could not be opened for read-only inspection.",
  ]),
  INPUT_CHANGED: definition([
    "error",
    "input",
    "needs_review",
    "none",
    "EPUB changed after selection",
    "The selected file no longer matches the reviewed snapshot.",
  ]),
  ZIP_INVALID: definition([
    "critical",
    "archive",
    "unsupported",
    "none",
    "ZIP archive is invalid",
    "The source is not a complete readable ZIP archive.",
  ]),
  ZIP_EMPTY: definition([
    "error",
    "archive",
    "unsupported",
    "none",
    "ZIP archive is empty",
    "The archive contains no entries.",
  ]),
  ZIP_MULTIDISK: definition([
    "critical",
    "archive",
    "unsafe",
    "none",
    "Multi-disk ZIP is unsupported",
    "The archive spans multiple disks and cannot be processed safely.",
  ]),
  ZIP64_INVALID: definition([
    "critical",
    "archive",
    "unsafe",
    "none",
    "ZIP64 metadata is invalid",
    "ZIP64 metadata is malformed or outside safe integer bounds.",
  ]),
  ZIP_METHOD_UNSUPPORTED: definition([
    "critical",
    "archive",
    "unsafe",
    "none",
    "ZIP compression method is unsupported",
    "An archive entry does not use STORE or DEFLATE compression.",
  ]),
  ZIP_CRC_MISMATCH: definition([
    "critical",
    "archive",
    "unsafe",
    "none",
    "ZIP checksum does not match",
    "An entry's streamed bytes do not match its declared checksum.",
  ]),
  ZIP_SIZE_MISMATCH: definition([
    "critical",
    "archive",
    "unsafe",
    "none",
    "ZIP size does not match",
    "An entry's streamed bytes do not match its declared size.",
  ]),
  ARCHIVE_SOURCE_TOO_LARGE: definition([
    "critical",
    "archive",
    "unsafe",
    "none",
    "Archive source is too large",
    "The compressed source exceeds the inspection limit.",
  ]),
  ARCHIVE_TOO_MANY_ENTRIES: definition([
    "critical",
    "archive",
    "unsafe",
    "none",
    "Archive has too many entries",
    "The archive entry count exceeds the inspection limit.",
  ]),
  ARCHIVE_ENTRY_TOO_LARGE: definition([
    "critical",
    "archive",
    "unsafe",
    "none",
    "Archive entry is too large",
    "An expanded entry exceeds the inspection limit.",
  ]),
  ARCHIVE_EXPANDED_TOO_LARGE: definition([
    "critical",
    "archive",
    "unsafe",
    "none",
    "Expanded archive is too large",
    "The total expanded size exceeds the inspection limit.",
  ]),
  ARCHIVE_COMPRESSION_RATIO: definition([
    "critical",
    "archive",
    "unsafe",
    "none",
    "Archive expansion ratio is unsafe",
    "The archive expansion ratio exceeds the inspection limit.",
  ]),
  ARCHIVE_TIMEOUT: definition([
    "critical",
    "archive",
    "unsafe",
    "none",
    "Archive inspection timed out",
    "Inspection exceeded the per-file time limit.",
  ]),
  ARCHIVE_PATH_ABSOLUTE: definition([
    "critical",
    "archive",
    "unsafe",
    "none",
    "Archive path is absolute",
    "An entry uses an absolute path.",
  ]),
  ARCHIVE_PATH_TRAVERSAL: definition([
    "critical",
    "archive",
    "unsafe",
    "none",
    "Archive path escapes its root",
    "An entry contains an escaping or noncanonical path segment.",
  ]),
  ARCHIVE_PATH_INVALID: definition([
    "critical",
    "archive",
    "unsafe",
    "none",
    "Archive path is invalid",
    "An entry name cannot be represented as a safe internal path.",
  ]),
  ARCHIVE_ENTRY_DUPLICATE: definition([
    "critical",
    "archive",
    "unsafe",
    "none",
    "Archive entry is duplicated",
    "More than one entry uses the same internal path.",
  ]),
  ARCHIVE_CASE_COLLISION: definition([
    "critical",
    "archive",
    "unsafe",
    "none",
    "Archive paths collide by case",
    "Multiple entries have canonically equivalent internal paths.",
  ]),
  ARCHIVE_FILE_DIRECTORY_CONFLICT: definition([
    "critical",
    "archive",
    "unsafe",
    "none",
    "Archive paths conflict",
    "File and directory paths have conflicting ancestry.",
  ]),
  ARCHIVE_SYMLINK: definition([
    "critical",
    "archive",
    "unsafe",
    "none",
    "Archive contains a symbolic link",
    "Symbolic links are not safe EPUB resources.",
  ]),
  ARCHIVE_SPECIAL_FILE: definition([
    "critical",
    "archive",
    "unsafe",
    "none",
    "Archive contains a special file",
    "An entry is neither a regular file nor a directory.",
  ]),
  ARCHIVE_ENCRYPTED_ENTRY: definition([
    "critical",
    "archive",
    "unsafe",
    "none",
    "Archive entry is encrypted",
    "ZIP-level encryption prevents safe inspection.",
  ]),
  MIMETYPE_MISSING: definition([
    "error",
    "mimetype",
    "repairable",
    "automatic",
    "Mimetype is missing",
    "The required root mimetype entry is absent.",
    "write_canonical_mimetype",
  ]),
  MIMETYPE_NOT_FIRST: definition([
    "error",
    "mimetype",
    "repairable",
    "automatic",
    "Mimetype is not first",
    "The mimetype entry is not the first physical archive entry.",
    "write_canonical_mimetype",
  ]),
  MIMETYPE_COMPRESSED: definition([
    "error",
    "mimetype",
    "repairable",
    "automatic",
    "Mimetype is compressed",
    "The mimetype entry must use STORE compression.",
    "write_canonical_mimetype",
  ]),
  MIMETYPE_VALUE_INVALID: definition([
    "error",
    "mimetype",
    "repairable",
    "automatic",
    "Mimetype value is invalid",
    "The mimetype value is not exactly application/epub+zip.",
    "write_canonical_mimetype",
  ]),
  MIMETYPE_EXTRA_FIELD: definition([
    "warning",
    "mimetype",
    "repairable",
    "automatic",
    "Mimetype has an extra field",
    "The mimetype local header contains disallowed extra data.",
    "write_canonical_mimetype",
  ]),
  CONTAINER_MISSING: definition([
    "error",
    "container",
    "needs_review",
    "conditional",
    "Container document is missing",
    "META-INF/container.xml is absent.",
    "rebuild_container_for_single_opf",
  ]),
  CONTAINER_XML_INVALID: definition([
    "error",
    "container",
    "needs_review",
    "conditional",
    "Container XML is invalid",
    "The container document could not be parsed safely.",
    "rebuild_container_for_single_opf",
  ]),
  CONTAINER_ROOTFILE_MISSING: definition([
    "error",
    "container",
    "needs_review",
    "conditional",
    "Container rootfile is missing",
    "The container has no usable package rootfile.",
    "rebuild_container_for_single_opf",
  ]),
  CONTAINER_ROOTFILE_MULTIPLE: definition([
    "warning",
    "container",
    "needs_review",
    "none",
    "Container has multiple rootfiles",
    "Multiple plausible package documents are declared.",
  ]),
  CONTAINER_PACKAGE_MISSING: definition([
    "error",
    "container",
    "needs_review",
    "conditional",
    "Referenced package is missing",
    "The package document referenced by the container does not exist.",
    "rebuild_container_for_single_opf",
  ]),
  PACKAGE_NOT_FOUND: definition([
    "error",
    "package",
    "unsupported",
    "none",
    "Package document was not found",
    "No valid EPUB package document exists.",
  ]),
  PACKAGE_AMBIGUOUS: definition([
    "error",
    "package",
    "needs_review",
    "none",
    "Package document is ambiguous",
    "Multiple plausible package documents exist.",
  ]),
  PACKAGE_XML_INVALID: definition([
    "error",
    "package",
    "needs_review",
    "none",
    "Package XML is invalid",
    "The selected package document could not be parsed safely.",
  ]),
  PACKAGE_VERSION_UNSUPPORTED: definition([
    "error",
    "package",
    "unsupported",
    "none",
    "EPUB version is unsupported",
    "The package version is outside the supported EPUB 2 and EPUB 3 scope.",
  ]),
  METADATA_TITLE_MISSING: definition([
    "warning",
    "package",
    "needs_review",
    "none",
    "Title metadata is missing",
    "The package has no non-empty title.",
  ]),
  METADATA_IDENTIFIER_MISSING: definition([
    "warning",
    "package",
    "needs_review",
    "none",
    "Identifier metadata is missing",
    "The package has no non-empty identifier.",
  ]),
  METADATA_LANGUAGE_MISSING: definition([
    "warning",
    "package",
    "needs_review",
    "none",
    "Language metadata is missing",
    "The package has no non-empty language.",
  ]),
  PACKAGE_UNIQUE_IDENTIFIER_INVALID: definition([
    "error",
    "package",
    "needs_review",
    "none",
    "Unique identifier is invalid",
    "The package unique-identifier does not resolve to exactly one identifier.",
  ]),
  MANIFEST_MISSING: definition([
    "error",
    "package",
    "needs_review",
    "none",
    "Manifest is missing",
    "The package manifest is absent or unusable.",
  ]),
  MANIFEST_ID_DUPLICATE: definition([
    "error",
    "package",
    "needs_review",
    "none",
    "Manifest ID is duplicated",
    "Multiple manifest items use the same ID.",
  ]),
  MANIFEST_HREF_DUPLICATE: definition([
    "warning",
    "package",
    "needs_review",
    "none",
    "Manifest resource is duplicated",
    "Multiple manifest items address the same resource.",
  ]),
  MANIFEST_RESOURCE_MISSING: definition([
    "error",
    "package",
    "needs_review",
    "none",
    "Manifest resource is missing",
    "A manifest target does not exist in the archive.",
  ]),
  MANIFEST_MEDIA_TYPE_MISMATCH: definition([
    "warning",
    "package",
    "repairable",
    "automatic",
    "Manifest media type does not match",
    "The declared media type conflicts with the resource extension.",
    "correct_manifest_media_type",
  ]),
  MANIFEST_MEDIA_TYPE_UNKNOWN: definition([
    "warning",
    "package",
    "needs_review",
    "none",
    "Manifest media type is unknown",
    "A resource type cannot be inferred safely.",
  ]),
  SPINE_MISSING: definition([
    "error",
    "package",
    "needs_review",
    "none",
    "Spine is missing",
    "The package spine is absent or unusable.",
  ]),
  SPINE_ITEMREF_MISSING_ID: definition([
    "error",
    "package",
    "needs_review",
    "none",
    "Spine item has no ID reference",
    "A spine itemref does not identify a manifest item.",
  ]),
  SPINE_ITEM_NOT_IN_MANIFEST: definition([
    "error",
    "package",
    "needs_review",
    "none",
    "Spine item is not in the manifest",
    "A spine ID reference has no matching manifest item.",
  ]),
  SPINE_READING_ORDER_INVALID: definition([
    "error",
    "package",
    "needs_review",
    "none",
    "Reading order is invalid",
    "The spine has no valid linear reading order.",
  ]),
  NAVIGATION_MISSING: definition([
    "warning",
    "package",
    "needs_review",
    "none",
    "Navigation document is missing",
    "The required EPUB navigation document is absent.",
  ]),
  NAVIGATION_AMBIGUOUS: definition([
    "warning",
    "package",
    "needs_review",
    "none",
    "Navigation document is ambiguous",
    "Multiple plausible navigation documents exist.",
  ]),
  COVER_MISSING: definition([
    "warning",
    "package",
    "healthy",
    "none",
    "Cover is missing",
    "No identifiable cover resource exists.",
  ]),
  COVER_AMBIGUOUS: definition([
    "warning",
    "package",
    "healthy",
    "none",
    "Cover is ambiguous",
    "Multiple plausible cover resources exist.",
  ]),
  XML_ENCODING_INVALID: definition([
    "error",
    "content",
    "needs_review",
    "conditional",
    "XML encoding is invalid",
    "The XML encoding cannot be decoded unambiguously.",
    "normalize_xml_encoding",
  ]),
  XML_VERSION_UNSUPPORTED: definition([
    "critical",
    "content",
    "unsafe",
    "none",
    "XML version is unsupported",
    "The document uses an unsupported XML version.",
  ]),
  XML_DOCTYPE_FORBIDDEN: definition([
    "critical",
    "content",
    "unsafe",
    "none",
    "XML DOCTYPE is forbidden",
    "The document contains a forbidden DOCTYPE declaration.",
  ]),
  XML_ENTITY_FORBIDDEN: definition([
    "critical",
    "content",
    "unsafe",
    "none",
    "XML entity is forbidden",
    "The document requests forbidden entity behavior.",
  ]),
  XML_TOO_LARGE: definition([
    "critical",
    "content",
    "unsafe",
    "none",
    "XML document is too large",
    "The XML document exceeds the parsing limit.",
  ]),
  XML_TOO_DEEP: definition([
    "critical",
    "content",
    "unsafe",
    "none",
    "XML document is too deep",
    "The XML nesting depth exceeds the parsing limit.",
  ]),
  XHTML_MALFORMED: definition([
    "error",
    "content",
    "needs_review",
    "none",
    "XHTML is malformed",
    "A content document could not be parsed safely.",
  ]),
  CONTENT_LINK_BROKEN: definition([
    "warning",
    "content",
    "needs_review",
    "conditional",
    "Internal link is broken",
    "An internal link target does not exist.",
    "correct_unique_reference",
  ]),
  CONTENT_IMAGE_MISSING: definition([
    "error",
    "content",
    "needs_review",
    "conditional",
    "Image is missing",
    "An image reference target does not exist.",
    "correct_unique_reference",
  ]),
  CONTENT_STYLESHEET_MISSING: definition([
    "warning",
    "content",
    "needs_review",
    "conditional",
    "Stylesheet is missing",
    "A stylesheet reference target does not exist.",
    "correct_unique_reference",
  ]),
  CONTENT_FONT_MISSING: definition([
    "warning",
    "content",
    "needs_review",
    "conditional",
    "Font is missing",
    "A font reference target does not exist.",
    "correct_unique_reference",
  ]),
  CONTENT_PATH_CASE_MISMATCH: definition([
    "warning",
    "content",
    "repairable",
    "automatic",
    "Reference path case does not match",
    "A reference differs only by canonical case from exactly one resource.",
    "normalize_equivalent_internal_path",
  ]),
  CONTENT_REMOTE_RESOURCE: definition([
    "warning",
    "content",
    "needs_review",
    "none",
    "Content uses a remote resource",
    "A content document references a remote resource.",
  ]),
  CONTENT_EXTERNAL_FILE_REFERENCE: definition([
    "critical",
    "content",
    "unsafe",
    "none",
    "Content references an external file",
    "A local reference escapes the EPUB archive.",
  ]),
  CONTENT_RELEVANT_FILE_EMPTY: definition([
    "warning",
    "content",
    "needs_review",
    "none",
    "Relevant resource is empty",
    "A required content or resource file has no bytes.",
  ]),
  CONTENT_CHAPTER_EMPTY: definition([
    "warning",
    "content",
    "needs_review",
    "none",
    "Chapter is empty",
    "A spine chapter has no deterministic useful content.",
  ]),
  CONTENT_SCRIPTED: definition([
    "warning",
    "compatibility",
    "needs_review",
    "none",
    "Content uses scripts",
    "Active scripted content may not be Kindle-compatible.",
  ]),
  CONTENT_EXECUTABLE_RESOURCE: definition([
    "critical",
    "content",
    "unsafe",
    "none",
    "Content includes an executable resource",
    "An executable or macro-like resource is present.",
  ]),
  CONTENT_FIXED_LAYOUT: definition([
    "info",
    "compatibility",
    "healthy",
    "none",
    "Publication uses fixed layout",
    "Fixed-layout content may have limited Kindle compatibility.",
  ]),
  CONTENT_INTERACTIVE: definition([
    "warning",
    "compatibility",
    "needs_review",
    "none",
    "Content is interactive",
    "Interactive content may not be supported on Kindle.",
  ]),
  CONTENT_ENCRYPTED: definition([
    "critical",
    "content",
    "unsafe",
    "none",
    "Content is encrypted",
    "Protected content cannot be inspected or repaired.",
  ]),
} as const satisfies Record<FindingCode, FindingDefinition>;

export interface CreateFindingOptions {
  readonly location?: FindingLocation;
  readonly targetIdentifier?: string;
  readonly evidence?: FindingEvidence;
  readonly repairability?: Repairability;
  readonly stateImpact?: FindingStateImpact;
  readonly recommendedRepair?: RepairKind;
  readonly description?: string;
}

export function createFinding(code: FindingCode, options: CreateFindingOptions = {}): Finding {
  const catalogued = FINDING_CATALOG[code];
  const repairability =
    options.repairability ?? (catalogued.repairability === "conditional" ? "none" : catalogued.repairability);
  const recommendedRepair =
    repairability === "automatic" ? (options.recommendedRepair ?? catalogued.recommendedRepair) : undefined;

  return {
    identity: createFindingIdentity(code, options.location, options.targetIdentifier),
    code,
    severity: catalogued.severity,
    category: catalogued.category,
    title: catalogued.title,
    description: options.description ?? catalogued.description,
    ...(options.location === undefined ? {} : { location: options.location }),
    ...(options.targetIdentifier === undefined ? {} : { targetIdentifier: options.targetIdentifier }),
    repairability,
    ...(recommendedRepair === undefined ? {} : { recommendedRepair }),
    revalidation: "not_compared",
    evidence: options.evidence ?? {},
    stateImpact: options.stateImpact ?? catalogued.stateImpact,
  };
}

export function isFindingCode(value: string): value is FindingCode {
  return (FINDING_CODES as readonly string[]).includes(value);
}

export const findingCatalog = FINDING_CATALOG;
export const createCatalogFinding = createFinding;
